name: Gatsby Publish

on:
  push:
    branches: [ main ]

jobs:
  depoly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: enriikke/gatsby-gh-pages-action@v2.1.1
        with:
          access-token: ${{ secrets.DBC }}
          deploy-branch: gh-pages
          gatsby-args: --prefix-paths

